M48
; DRILL file {KiCad 6.0.0-d3dd2cf0fa~116~ubuntu21.10.1} date Sat Feb 12 15:32:37 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-12T15:32:37+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.0-d3dd2cf0fa~116~ubuntu21.10.1
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
%
G90
G05
T1
X5.8773Y-3.8859
X6.1773Y-3.8859
T0
M30
